# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            gameKnife
tagline:          'a graphic artisan'
description:      'A Graphic Artisan.'
url:              http://gameknife.github.io
baseurl:          /

#category
cate:
  tech:			  tech
  life:			  life
  art:			  art
  hidden:     hidden

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
  
# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: kaimingyi@163.com
  facebook:
  flickr:
  github: gameknife
  instagram: gameknife
  linkedin: kaimingyi
  pinterest:
  rss: do# just type anything here for a working RSS icon, make sure you set the "url" above!
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>

# resume things

name: Yi Kaiming
job: game develop engineer
location: Chengdu, China
languages: Game & Graphic Development, and an enthusiastic gamer, definitely.
email_address: kaimingyi@163.com
github_username: gameknife